# -*- coding: utf-8 -*-
"""UJIAN_PRAKTEK_PEBRYAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4MkY0WoaFNFfDTH434GJbfpeiIBQN-l
"""

## Soal Pratikum No.1 - Array & Python List

nilai = [70, 80, 90, 75, 85]

def tampil_nilai():
  print("\nDaftar Nilai:", nilai)

def tambah_nilai():
  n = int(input("Masukkan nilai baru: "))
  nilai.append(n)
  print("Nilai berhasil ditambahkan")

def hapus_nilai():
  n = int(input("Masukkan nilai yang akan dihapus: "))

  if n in nilai:
    nilai.remove(n)
    print("Nilai berhasil dihapus")

  else:
    print("Nilai tidak ditemukan")

def rata_rata():
  avg = sum(nilai)/len(nilai)
  print("Rata-rata: ", avg)

def min_max():
  print("Nilai tertinggi: ", max(nilai))
  print("Nilai terendah: ", min(nilai))

while True:
  print("\nMenu:")
  print("1. Tampilkan Nilai")
  print("2. Tambah Nilai")
  print("3. Hapus Nilai")
  print("4. Rata-rata Nilai")
  print("5. Nilai Tertinggi dan Nilai Terendah")
  print("6. Keluar")

  pilih = input("Pilih menu: ")

  if pilih == '1':
    tampil_nilai()
  elif pilih == '2':
    tambah_nilai()
  elif pilih == '3':
    hapus_nilai()
  elif pilih == '4':
    rata_rata()
  elif pilih == '5':
    min_max()
  elif pilih == '6':
    print("Program selesai")
    break
  else:
    print("Tidak tersedia")

## Soal Pratikum No.2 - Linked List

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    def insert_awal(self, data):
        node_baru = Node(data)

        node_baru.next = self.head
        self.head = node_baru

    def insert_akhir(self, data):
        node_baru = Node(data)

        if self.head is None:
            self.head = node_baru
            return

        temp = self.head

        while temp.next:
            temp = temp.next

        temp.next = node_baru

    def tampil(self):

        if self.head is None:
            print("List kosong")
            return

        temp = self.head

        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next

        print("None")

    def cari(self, key):

        temp = self.head

        while temp:

            if temp.data == key:
                return True

            temp = temp.next

        return False

    def hapus(self, key):

        temp = self.head

        if temp and temp.data == key:
            self.head = temp.next
            return

        prev = None

        while temp and temp.data != key:
            prev = temp
            temp = temp.next

        if temp is None:
            return

        prev.next = temp.next

ll = LinkedList()

ll.insert_akhir(10)
ll.insert_akhir(20)
ll.insert_akhir(30)
ll.insert_akhir(40)

print("Hasil Linked List:")
ll.tampil()

cari = 30

print("\nCari data", cari)

if ll.cari(cari):
    print("Data ditemukan")
else:
    print("Data tidak ditemukan")

print("\nHapus data 20")

ll.hapus(20)

ll.tampil()

## Soal Pratikum No.3 - Sistem Manajemen Playlist Musik

class Node:
    def __init__(self, judul, penyanyi):
        self.judul = judul
        self.penyanyi = penyanyi

        self.next = None
        self.prev = None


class CircularDoublyLinkedList:

    def __init__(self):
        self.head = None
        self.current = None

    def tambah_lagu(self, judul, penyanyi):

        baru = Node(judul, penyanyi)

        if self.head is None:

            self.head = baru

            baru.next = baru
            baru.prev = baru

            self.current = baru

        else:

            tail = self.head.prev

            tail.next = baru

            baru.prev = tail

            baru.next = self.head

            self.head.prev = baru

    def hapus_lagu(self, judul):

        if self.head is None:
            print("Playlist kosong")
            return

        temp = self.head

        while True:

            if temp.judul.lower() == judul.lower():

                if temp.next == temp:

                    self.head = None
                    self.current = None

                else:

                    temp.prev.next = temp.next
                    temp.next.prev = temp.prev

                    if temp == self.head:
                        self.head = temp.next

                    if temp == self.current:
                        self.current = temp.next

                print("Lagu dihapus")
                return

            temp = temp.next

            if temp == self.head:
                break

        print("Lagu tidak ditemukan")

    def tampilkan(self):

        if self.head is None:
            print("Playlist kosong")
            return

        temp = self.head
        no = 1

        print("\nPlaylist:")

        while True:

            print(
                f"{no}. {temp.judul} - {temp.penyanyi}"
            )

            temp = temp.next

            no += 1

            if temp == self.head:
                break

    def next_lagu(self):

        if self.current:
            self.current = self.current.next

            print(
                "Now Playing:",
                self.current.judul,
                "-",
                self.current.penyanyi
            )

    def prev_lagu(self):

        if self.current:
            self.current = self.current.prev

            print(
                "Now Playing:",
                self.current.judul,
                "-",
                self.current.penyanyi
            )

    def cari(self, judul):

        if self.head is None:
            return

        temp = self.head

        while True:

            if temp.judul.lower() == judul.lower():

                print(
                    "Ditemukan:",
                    temp.judul,
                    "-",
                    temp.penyanyi
                )

                return

            temp = temp.next

            if temp == self.head:
                break

        print("Lagu tidak ditemukan")


playlist = CircularDoublyLinkedList()

while True:

    print("\n===== MENU PLAYLIST =====")
    print("1. Tambah Lagu")
    print("2. Hapus Lagu")
    print("3. Tampilkan Playlist")
    print("4. Next Lagu")
    print("5. Prev Lagu")
    print("6. Cari Lagu")
    print("7. Keluar")

    try:
        pilih = int(input("Pilih: "))
    except ValueError:
        print("Input tidak valid. Masukkan angka antara 1-7.")
        continue

    if pilih == 1:

        judul = input("Judul: ")
        penyanyi = input("Penyanyi: ")

        playlist.tambah_lagu(
            judul,
            penyanyi
        )

    elif pilih == 2:

        judul = input(
            "Judul lagu dihapus: "
        )

        playlist.hapus_lagu(judul)

    elif pilih == 3:

        playlist.tampilkan()

    elif pilih == 4:

        playlist.next_lagu()

    elif pilih == 5:

        playlist.prev_lagu()

    elif pilih == 6:

        judul = input(
            "Cari judul: "
        )

        playlist.cari(judul)

    elif pilih == 7:

        print("Program selesai")
        break

    else:
        print("Pilihan tidak tersedia. Masukkan angka antara 1-7.")
        continue